[package]
name = "delax"
version = "0.2.0"
edition = "2024"
authors = ["Ava Wallenfang <ava@wallenfang.de>"]
license = "MIT"
homepage = "https://windsonix.com"
description = "A delay plugin with a few bells and whistles"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
nice-plug = { git = "https://codeberg.org/RustAudio/nice-plug.git", default-features = false, features = ["standalone", "editor"] }
crossbeam = "0.8.4"
serde = { version = "1.0.228", features = ["derive"] }
slint = { version="1.16.1" }
baseview = { version = "0.3.1", features = ["opengl"] }
rustfft = "6.4.1"
rtrb = "0.4.0"

[build-dependencies]
slint-build = "1.16.1"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
