[package]
name = "delax"
version = "0.1.0"
edition = "2024"
authors = ["Ava Wallenfang <ava@wallenfang.de>"]
license = "MIT"
homepage = "https://ritzin.dev"
description = "A delay plugin with a few bells and whistles"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
# Remove the `assert_process_allocs` feature to allow allocations on the audio
# thread in debug builds.
nice-plug = { git = "https://codeberg.org/RustAudio/nice-plug.git", default-features = false, features = ["standalone", "editor"] }
# Uncomment the below line to disable the on-by-default VST3 feature to remove
# the GPL compatibility requirement
# nice_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", default_features = false, features = ["assert_process_allocs"] }

crossbeam = "0.8.4"
serde = { version = "1.0.228", features = ["derive"] }
slint = { version="1.16.1" }
baseview = { version = "0.3.1", features = ["opengl"] }

[build-dependencies]
slint-build = "1.16.1"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
