import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch, Spinner, HorizontalBox
} from "std-widgets.slint";
import { ParamKnob } from "../components/param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "../components/param_switch.slint";
import { Palette } from "../global.slint";
import { PeakMeter } from "../components/peak_meter.slint";
import { SpectrumAnalyzer } from "../components/spectrum_analyzer.slint";
import { Button } from "../components/button.slint";

export component AboutPage inherits VerticalLayout {
    in property <string> version;
    padding-left: 20px;
    padding-right: 20px;
    spacing: 6px;
    Text {
        text: "Built by Ritzin Dev";
        color: Palette.text;
        font-size: 17pt;
    }
    Text {
        text: "Version: " + root.version;
        color: Palette.text;
    }
    Text {
        text: "Used dependencies:";
        color: Palette.text;
    }
    StyledText {
        text: @markdown("[Nice-Plug (ISC)](https://codeberg.org/RustAudio/nice-plug.git)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    StyledText {
        text: @markdown("[Crossbeam (MIT)](https://github.com/crossbeam-rs/crossbeam)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    StyledText {
        text: @markdown("[Serde (MIT)](https://github.com/serde-rs/serde)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    StyledText {
        text: @markdown("[Slint (Royalty free)](https://github.com/slint-ui/slint)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    StyledText {
        text: @markdown("[Baseview (MIT)](https://github.com/RustAudio/baseview)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    StyledText {
        text: @markdown("[RustFFT (MIT)](https://github.com/ejmahler/RustFFT)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    StyledText {
        text: @markdown("[rtrb (MIT)](https://github.com/mgeier/rtrb)");
        link-color: Palette.secondary;
        link-clicked(url) => { Platform.open-url(url); }
    }
    AboutSlint { }
}
