import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch, Spinner, HorizontalBox
} from "std-widgets.slint";
import { ParamKnob } from "../components/param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "../components/param_switch.slint";
import { Palette } from "../components/global.slint";
import { PeakMeter } from "../components/peak_meter.slint";
import { SpectrumAnalyzer } from "../components/spectrum_analyzer.slint";
import { Button } from "../components/button.slint";

export component AboutPage inherits VerticalLayout {
    HorizontalLayout {
        alignment: center;
        Image {
            source: @image-url("../assets/logo.svg");
            width: 100px;
            height: 50px;
            horizontal-alignment: ImageHorizontalAlignment.center;
            image-fit: ImageFit.contain;
        }
    }
    Text {
        text: "Built by Ritzin Dev";
        color: Palette.text;
    }
    Text {
        text: "Version: 0.2.0";
        color: Palette.text;
    }
}