import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch,
    Spinner,
    HorizontalBox,
} from "std-widgets.slint";
import { ParamKnob } from "../components/param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "../components/param_switch.slint";
import { Palette } from "../components/global.slint";
import { PeakMeter } from "../components/peak_meter.slint";
import { SpectrumAnalyzer } from "../components/spectrum_analyzer.slint";
import { Button } from "../components/button.slint";
import { Timing } from "../components/timing.slint";
import { IconButton } from "../components/icon_button.slint";
import { DecayVisualizer } from "../components/decay_visualizer.slint";

export component DelayPage inherits Rectangle {
    in-out property <bool> is_stereo: false;
    in-out property <bool> is_bpm_bound_l: false;
    in-out property <bool> is_bpm_bound_r: false;
    in-out property <string> timing_display_l: "2 16th";
    in-out property <string> timing_display_r: "2 16th";
    in-out property <float> timing_factor_l: 1.0;
    in-out property <float> timing_factor_r: 1.0;
    in-out property <float> bpm: 120.0;
    property <int> open_page: 0;

    clip: true;
    background: transparent;
    vertical-stretch: 1;

    VerticalLayout {
        width: 100%;
        height: 100%;
        DecayVisualizer {
            width: 100%;
            height: 50%;
            feedback_l: ParamBus.read_val("feedback_l");
            feedback_r: ParamBus.read_val("feedback_r");
            time_l: ParamBus.read_val("delay_l");
            time_r: ParamBus.read_val("delay_r");
            time_note_l: ParamBus.read_val("delay_note_l");
            time_note_r: ParamBus.read_val("delay_note_r");
            time_div_l: ParamBus.read_val("delay_div_l");
            time_div_r: ParamBus.read_val("delay_div_r");
            bpm_bound_l: root.is_bpm_bound_l;
            bpm_bound_r: root.is_bpm_bound_r;
            is_stereo: root.is_stereo;
            bpm: root.bpm;
        }
        // Placeholder for buffer
        Rectangle {
            height: 50%;
            background: Palette.background-light;
        }
    }

    HorizontalLayout {
        alignment: end;
        VerticalLayout {
            width: 50%;
            height: 100%;
            padding: 6px;
            spacing: 4px;
            HorizontalLayout {
                height: 22px;
                alignment: LayoutAlignment.center;
                spacing: 10px;
                Text {
                    text: "Mono";
                    color: Palette.text;
                    vertical-alignment: center;
                }

                ParamSwitch {
                    param_name: "stereo";
                    checked <=> root.is_stereo;
                }

                Text {
                    text: "Stereo";
                    color: Palette.text;
                    vertical-alignment: center;
                }
            }

            if !root.is_stereo:
                    VerticalLayout {
                vertical-stretch: 1;
                spacing: 4px;
                padding-left: 8px;
                padding-right: 8px;

                HorizontalLayout {
                    vertical-stretch: 1;
                    min-height: 45px;
                    alignment: LayoutAlignment.space-between;
                    Text {
                        text: "EQ";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    ParamKnob {
                        param_name: "input_svf_cutoff_l";
                        label: "Cutoff";
                        val: ParamBus.read_val("input_svf_cutoff_l");
                        display_val: ParamBus.read_display_val("input_svf_cutoff_l");
                    }

                    ParamKnob {
                        param_name: "input_svf_res_l";
                        label: "Res";
                        val: ParamBus.read_val("input_svf_res_l");
                        display_val: ParamBus.read_display_val("input_svf_res_l");
                    }
                }

                HorizontalLayout {
                    vertical-stretch: 1.6;
                    min-height: 75px;
                    alignment: LayoutAlignment.space-between;
                    Text {
                        text: "Delay";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    Timing {
                        bpm_param: "bpm_bound_l";
                        ms_param: "delay_l";
                        note_param: "delay_note_l";
                        div_param: "delay_div_l";
                        selected_factor: root.timing_factor_l;
                        note_display: root.timing_display_l;
                        time_ms: ParamBus.read_val("delay_l");
                        display_time_ms: ParamBus.read_display_val("delay_l");
                        time_16th: ParamBus.read_val("delay_note_l");
                        bpm_bound <=> root.is_bpm_bound_l;
                    }
                }

                HorizontalLayout {
                    vertical-stretch: 1;
                    min-height: 55px;
                    alignment: LayoutAlignment.space-between;
                    Text {
                        text: "Mix";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    ParamKnob {
                        param_name: "feedback_l";
                        label: "Feedback";
                        val: ParamBus.read_val("feedback_l");
                        display_val: ParamBus.read_display_val("feedback_l");
                    }

                    ParamKnob {
                        param_name: "wetness";
                        label: "Wetness";
                        val: ParamBus.read_val("wetness");
                        display_val: ParamBus.read_display_val("wetness");
                    }
                }

                Rectangle {
                    vertical-stretch: 1;
                }
            }

            if root.is_stereo:
                    VerticalLayout {
                vertical-stretch: 1;
                spacing: 4px;
                padding-left: 8px;
                padding-right: 8px;

                HorizontalLayout {
                    height: 26px;
                    alignment: LayoutAlignment.center;
                    spacing: 8px;
                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: open_page == 0;
                        Text {
                            text: "L";
                            color: Palette.text;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }

                        clicked => {
                            open_page = 0;
                        }
                    }

                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: open_page == 1;
                        Text {
                            text: "R";
                            color: Palette.text;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }

                        clicked => {
                            open_page = 1;
                        }
                    }
                }

                if open_page == 0:
                        VerticalLayout {
                    vertical-stretch: 1;
                    spacing: 4px;

                    HorizontalLayout {
                        vertical-stretch: 1;
                        min-height: 45px;
                        alignment: LayoutAlignment.space-between;
                        Text {
                            text: "EQ";
                            color: Palette.text;
                            vertical-alignment: center;
                        }

                        ParamKnob {
                            param_name: "input_svf_cutoff_l";
                            label: "Cutoff L";
                            val: ParamBus.read_val("input_svf_cutoff_l");
                            display_val: ParamBus.read_display_val("input_svf_cutoff_l");
                        }

                        ParamKnob {
                            param_name: "input_svf_res_l";
                            label: "Res L";
                            val: ParamBus.read_val("input_svf_res_l");
                            display_val: ParamBus.read_display_val("input_svf_res_l");
                        }
                    }

                    HorizontalLayout {
                        vertical-stretch: 1.6;
                        min-height: 75px;
                        alignment: LayoutAlignment.space-between;
                        Text {
                            text: "Delay";
                            color: Palette.text;
                            vertical-alignment: center;
                        }

                        Timing {
                            bpm_param: "bpm_bound_l";
                            ms_param: "delay_l";
                            note_param: "delay_note_l";
                            div_param: "delay_div_l";
                            selected_factor: root.timing_factor_l;
                            note_display: root.timing_display_l;
                            time_ms: ParamBus.read_val("delay_l");
                            display_time_ms: ParamBus.read_display_val("delay_l");
                            time_16th: ParamBus.read_val("delay_note_l");
                            bpm_bound <=> root.is_bpm_bound_l;
                        }
                    }

                    HorizontalLayout {
                        vertical-stretch: 1;
                        min-height: 55px;
                        alignment: LayoutAlignment.space-between;
                        Text {
                            text: "Mix";
                            color: Palette.text;
                            vertical-alignment: center;
                        }

                        ParamKnob {
                            param_name: "feedback_l";
                            label: "Feedback L";
                            val: ParamBus.read_val("feedback_l");
                            display_val: ParamBus.read_display_val("feedback_l");
                        }

                        ParamKnob {
                            param_name: "wetness";
                            label: "Wetness";
                            val: ParamBus.read_val("wetness");
                            display_val: ParamBus.read_display_val("wetness");
                        }
                    }
                }

                if open_page == 1:
                        VerticalLayout {
                    vertical-stretch: 1;
                    spacing: 4px;

                    HorizontalLayout {
                        vertical-stretch: 1;
                        min-height: 45px;
                        alignment: LayoutAlignment.space-between;
                        Text {
                            text: "EQ";
                            color: Palette.text;
                            vertical-alignment: center;
                        }

                        ParamKnob {
                            param_name: "input_svf_cutoff_r";
                            label: "Cutoff R";
                            val: ParamBus.read_val("input_svf_cutoff_r");
                            display_val: ParamBus.read_display_val("input_svf_cutoff_r");
                        }

                        ParamKnob {
                            param_name: "input_svf_res_r";
                            label: "Res R";
                            val: ParamBus.read_val("input_svf_res_r");
                            display_val: ParamBus.read_display_val("input_svf_res_r");
                        }
                    }

                    HorizontalLayout {
                        vertical-stretch: 1.6;
                        min-height: 75px;
                        alignment: LayoutAlignment.space-between;
                        Text {
                            text: "Delay";
                            color: Palette.text;
                            vertical-alignment: center;
                        }

                        Timing {
                            bpm_param: "bpm_bound_r";
                            ms_param: "delay_r";
                            note_param: "delay_note_r";
                            div_param: "delay_div_r";
                            selected_factor: root.timing_factor_r;
                            note_display: root.timing_display_r;
                            time_ms: ParamBus.read_val("delay_r");
                            display_time_ms: ParamBus.read_display_val("delay_r");
                            time_16th: ParamBus.read_val("delay_note_r");
                            bpm_bound <=> root.is_bpm_bound_r;
                        }
                    }

                    HorizontalLayout {
                        vertical-stretch: 1;
                        min-height: 55px;
                        alignment: LayoutAlignment.space-between;
                        Text {
                            text: "Mix";
                            color: Palette.text;
                            vertical-alignment: center;
                        }

                        ParamKnob {
                            param_name: "feedback_r";
                            label: "Feedback R";
                            val: ParamBus.read_val("feedback_r");
                            display_val: ParamBus.read_display_val("feedback_r");
                        }

                        ParamKnob {
                            param_name: "wetness";
                            label: "Wetness";
                            val: ParamBus.read_val("wetness");
                            display_val: ParamBus.read_display_val("wetness");
                        }
                    }
                }
            }
        }
    }
}
