import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch,
    Spinner,
    HorizontalBox,
} from "std-widgets.slint";
import { ParamKnob } from "../components/param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "../components/param_switch.slint";
import { Palette } from "../components/global.slint";
import { PeakMeter } from "../components/peak_meter.slint";
import { SpectrumAnalyzer } from "../components/spectrum_analyzer.slint";
import { Button } from "../components/button.slint";
import { Timing } from "../components/timing.slint";
import { IconButton } from "../components/icon_button.slint";
import { DecayVisualizer } from "../components/decay_visualizer.slint";

export component DelayPage inherits VerticalLayout {
    in-out property <bool> is_stereo: false;
    in-out property <bool> is_bpm_bound_l: false;
    in-out property <bool> is_bpm_bound_r: false;
    in-out property <string> timing_display_l: "2 16th";
    in-out property <string> timing_display_r: "2 16th";
    in-out property <float> timing_factor_l: 1.0;
    in-out property <float> timing_factor_r: 1.0;
    property <int> open_page: 0;
    alignment: end;
    // Bottom Layer
    Rectangle {
        width: 100%;
        height: 100%;
        z: 0;
        DecayVisualizer {
            feedback_l: ParamBus.read_val("feedback_l");
            feedback_r: ParamBus.read_val("feedback_r");
            time_l: ParamBus.read_val("delay_l");
            time_r: ParamBus.read_val("delay_r");
            is_stereo: is_stereo;
        }
    }
    // Top Layer
    Rectangle {
        width: 100%;
        height: 100%;
        z: 1;
        HorizontalLayout {
            accessible-role: AccessibleRole.none;
            alignment: LayoutAlignment.center;
            spacing: 10px;
            Text {
                text: "Mono";
                color: Palette.text;
            }

            ParamSwitch {
                param_name: "stereo";
                checked <=> root.is_stereo;
            }

            Text {
                text: "Stereo";
                color: Palette.text;
            }
        }

        if !root.is_stereo:
        VerticalLayout {
            width: 200px;
            HorizontalLayout {
                alignment: LayoutAlignment.space-between;
                height: 70px;
                Text {
                    text: "EQ";
                    color: Palette.text;
                    vertical-alignment: center;
                }

                ParamKnob {
                    param_name: "input_svf_cutoff_l";
                    label: "Cutoff";
                    val: ParamBus.read_val("input_svf_cutoff_l");
                    display_val: ParamBus.read_display_val("input_svf_cutoff_l");
                }

                ParamKnob {
                    param_name: "input_svf_res_l";
                    label: "Res";
                    val: ParamBus.read_val("input_svf_res_l");
                    display_val: ParamBus.read_display_val("input_svf_res_l");
                }
            }

            HorizontalLayout {
                alignment: LayoutAlignment.space-between;
                height: 115px;
                Text {
                    text: "Delay";
                    color: Palette.text;
                    vertical-alignment: center;
                }

                Timing {
                    bpm_param: "bpm_bound_l";
                    ms_param: "delay_l";
                    note_param: "delay_note_l";
                    div_param: "delay_div_l";
                    selected_factor: root.timing_factor_l;
                    note_display: root.timing_display_l;
                    time_ms: ParamBus.read_val("delay_l");
                    display_time_ms: ParamBus.read_display_val("delay_l");
                    time_16th: ParamBus.read_val("delay_note_l");
                    bpm_bound <=> root.is_bpm_bound_l;
                }
            }

            HorizontalLayout {
                alignment: LayoutAlignment.space-between;
                height: 82px;
                Text {
                    text: "Mix";
                    color: Palette.text;
                }

                ParamKnob {
                    param_name: "feedback_l";
                    label: "Feedback";
                    val: ParamBus.read_val("feedback_l");
                    display_val: ParamBus.read_display_val("feedback_l");
                }

                ParamKnob {
                    param_name: "wetness";
                    label: "Wetness";
                    val: ParamBus.read_val("wetness");
                    display_val: ParamBus.read_display_val("wetness");
                }
            }
        }
        if root.is_stereo:
        VerticalLayout {
            width: 200px;
            HorizontalLayout {
                width: 100px;
                IconButton {
                    width: 25px;
                    height: 25px;
                    checked: open_page == 0;
                    Text {
                        text: "L";
                        color: Palette.text;
                    }

                    clicked => {
                        open_page = 0;
                    }
                }

                IconButton {
                    width: 25px;
                    height: 25px;
                    checked: open_page == 1;
                    Text {
                        text: "R";
                        color: Palette.text;
                    }

                    clicked => {
                        open_page = 1;
                    }
                }
            }

            if open_page == 0:
            VerticalLayout {

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    height: 70px;
                    Text {
                        text: "EQ";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    ParamKnob {
                        param_name: "input_svf_cutoff_l";
                        label: "Cutoff L";
                        val: ParamBus.read_val("input_svf_cutoff_l");
                        display_val: ParamBus.read_display_val("input_svf_cutoff_l");
                    }

                    ParamKnob {
                        param_name: "input_svf_res_l";
                        label: "Res L";
                        val: ParamBus.read_val("input_svf_res_l");
                        display_val: ParamBus.read_display_val("input_svf_res_l");
                    }
                }

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    height: 115px;
                    Text {
                        text: "Delay";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    Timing {
                        bpm_param: "bpm_bound_l";
                        ms_param: "delay_l";
                        note_param: "delay_note_l";
                        div_param: "delay_div_l";
                        selected_factor: root.timing_factor_l;
                        note_display: root.timing_display_l;
                        time_ms: ParamBus.read_val("delay_l");
                        display_time_ms: ParamBus.read_display_val("delay_l");
                        time_16th: ParamBus.read_val("delay_note_l");
                        bpm_bound <=> root.is_bpm_bound_l;
                    }
                }

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    height: 82px;
                    Text {
                        text: "Mix";
                        color: Palette.text;
                    }

                    ParamKnob {
                        param_name: "feedback_l";
                        label: "Feedback L";
                        val: ParamBus.read_val("feedback_l");
                        display_val: ParamBus.read_display_val("feedback_l");
                    }

                    ParamKnob {
                        param_name: "wetness";
                        label: "Wetness";
                        val: ParamBus.read_val("wetness");
                        display_val: ParamBus.read_display_val("wetness");
                    }
                }
            }

            if open_page == 1:
            VerticalLayout {

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    height: 70px;
                    Text {
                        text: "EQ";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    ParamKnob {
                        param_name: "input_svf_cutoff_r";
                        label: "Cutoff R";
                        val: ParamBus.read_val("input_svf_cutoff_r");
                        display_val: ParamBus.read_display_val("input_svf_cutoff_r");
                    }

                    ParamKnob {
                        param_name: "input_svf_res_r";
                        label: "Res R";
                        val: ParamBus.read_val("input_svf_res_r");
                        display_val: ParamBus.read_display_val("input_svf_res_r");
                    }
                }

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    height: 115px;
                    Text {
                        text: "Delay";
                        color: Palette.text;
                        vertical-alignment: center;
                    }

                    Timing {
                        bpm_param: "bpm_bound_r";
                        ms_param: "delay_r";
                        note_param: "delay_note_r";
                        div_param: "delay_div_r";
                        selected_factor: root.timing_factor_r;
                        note_display: root.timing_display_r;
                        time_ms: ParamBus.read_val("delay_r");
                        display_time_ms: ParamBus.read_display_val("delay_r");
                        time_16th: ParamBus.read_val("delay_note_r");
                        bpm_bound <=> root.is_bpm_bound_r;
                    }
                }

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    height: 82px;
                    Text {
                        text: "Mix";
                        color: Palette.text;
                    }

                    ParamKnob {
                        param_name: "feedback_r";
                        label: "Feedback R";
                        val: ParamBus.read_val("feedback_r");
                        display_val: ParamBus.read_display_val("feedback_r");
                    }

                    ParamKnob {
                        param_name: "wetness";
                        label: "Wetness";
                        val: ParamBus.read_val("wetness");
                        display_val: ParamBus.read_display_val("wetness");
                    }
                }
            }
        }
    }
}
