import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch,
    Spinner,
    HorizontalBox,
} from "std-widgets.slint";
import { ParamKnob } from "../components/param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "../components/param_switch.slint";
import { Palette } from "../global.slint";
import { PeakMeter } from "../components/peak_meter.slint";
import { SpectrumAnalyzer } from "../components/spectrum_analyzer.slint";
import { Button } from "../components/button.slint";
import { Timing } from "../components/timing.slint";
import { IconButton } from "../components/icon_button.slint";
import { BufferVisualizer } from "../components/buffer_visualizer.slint";
import { GpuDecayVisualizer } from "../components/gpu_decay_visualizer.slint";

export component DelayPage inherits Rectangle {
    in property <image> buffer_tex;
    in property <image> decay_tex;
    in-out property <bool> is_stereo: false;
    in-out property <bool> is_ping_pong: false;
    in-out property <bool> is_bpm_bound_l: false;
    in-out property <bool> is_bpm_bound_r: false;
    in-out property <string> timing_display_l: "2 16th";
    in-out property <string> timing_display_r: "2 16th";
    in-out property <float> timing_factor_l: 1.0;
    in-out property <float> timing_factor_r: 1.0;
    in-out property <float> bpm: 120.0;
    in-out property <[float]> dry_buffer;
    in-out property <[float]> wet_buffer;
    property <int> open_page: 0;

    clip: true;
    background: transparent;
    vertical-stretch: 1;

    VerticalLayout {
        width: 100%;
        height: 100%;

        GpuDecayVisualizer {
            width: 100%;
            height: 50%;
            texture: decay_tex;
        }

        BufferVisualizer {
            texture: buffer_tex;
            /*width: 100%;
            height: 50%;
            dry_buffer: dry_buffer;
            wet_buffer: wet_buffer;
            wetness: ParamBus.read_val("wetness");*/
        }
    }

    HorizontalLayout {
        alignment: end;
        Rectangle {
            width: 50%;
            height: 100%;

            background: Palette.background-light;
            opacity: 0.8;
            border-width: 1px;
            border-color: Palette.secondary-muted;
            VerticalLayout {
                width: 100%;
                alignment: LayoutAlignment.stretch;
                height: 100%;
                padding: 6px;
                spacing: 4px;
                HorizontalLayout {
                    height: 25px;
                    width: 10%;
                    alignment: LayoutAlignment.center;
                    spacing: 10px;
                    if is_stereo:
                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: open_page == 0;
                        Text {
                            text: "L";
                            color: parent.checked ? Palette.text-dark : Palette.text;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }

                        clicked => {
                            open_page = 0;
                        }
                    }
                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: !root.is_stereo;
                        Image {
                            source: @image-url("../assets/mono.svg");
                            image-fit: contain;
                            colorize: parent.checked ? Palette.text-dark : Palette.text;
                        }

                        clicked => {
                            ParamBus.param_changed("stereo", 0.0);
                        }
                    }
                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: root.is_stereo && !is_ping_pong;
                        Image {
                            source: @image-url("../assets/stereo.svg");
                            image-fit: contain;
                            colorize: parent.checked ? Palette.text-dark : Palette.text;
                        }

                        clicked => {
                            ParamBus.param_changed("stereo", 0.5);
                        }
                    }
                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: root.is_ping_pong;
                        Image {
                            source: @image-url("../assets/pingpong.svg");
                            image-fit: contain;
                            colorize: parent.checked ? Palette.text-dark : Palette.text;
                        }

                        clicked => {
                            ParamBus.param_changed("stereo", 1.0);
                        }
                    }
                    if is_stereo:
                    IconButton {
                        width: 25px;
                        height: 25px;
                        checked: open_page == 1;
                        Text {
                            text: "R";
                            color: parent.checked ? Palette.text-dark : Palette.text;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }

                        clicked => {
                            open_page = 1;
                        }
                    }
                }

                if !root.is_stereo:
                    VerticalLayout {
                    vertical-stretch: 1;
                    spacing: 4px;
                    alignment: LayoutAlignment.stretch;
                        padding-left: 8px;
                    padding-right: 8px;

                    HorizontalLayout {
                        vertical-stretch: 1;
                        min-height: 45px;
                        alignment: LayoutAlignment.space-around;

                        ParamKnob {
                            param_name: "input_svf_cutoff_low_l";
                            label: "Low";
                            val: ParamBus.read_val("input_svf_cutoff_low_l");
                            display_val: ParamBus.read_display_val("input_svf_cutoff_low_l");
                        }
                        ParamKnob {
                            param_name: "input_svf_cutoff_high_l";
                            label: "High";
                            val: ParamBus.read_val("input_svf_cutoff_high_l");
                            display_val: ParamBus.read_display_val("input_svf_cutoff_high_l");
                        }
                    }

                    HorizontalLayout {
                        vertical-stretch: 1.6;
                        min-height: 75px;
                        alignment: LayoutAlignment.center;

                        Timing {
                            bpm_param: "bpm_bound_l";
                            ms_param: "delay_l";
                            note_param: "delay_note_l";
                            div_param: "delay_div_l";
                            selected_factor: root.timing_factor_l;
                            note_display: root.timing_display_l;
                            time_ms: ParamBus.read_val("delay_l");
                            display_time_ms: ParamBus.read_display_val("delay_l");
                            time_16th: ParamBus.read_val("delay_note_l");
                            bpm_bound <=> root.is_bpm_bound_l;
                        }
                    }

                    HorizontalLayout {
                        vertical-stretch: 1;
                        min-height: 55px;
                        alignment: LayoutAlignment.space-around;

                        ParamKnob {
                            param_name: "feedback_l";
                            label: "Feedback";
                            val: ParamBus.read_val("feedback_l");
                        }

                        ParamKnob {
                            param_name: "wetness";
                            label: "Wetness";
                            val: ParamBus.read_val("wetness");
                        }
                    }

                    Rectangle {
                        vertical-stretch: 1;
                    }
                }

                if root.is_stereo:
                    VerticalLayout {
                    vertical-stretch: 1;
                    spacing: 4px;
                    padding-left: 8px;
                    padding-right: 8px;

                    if open_page == 0:
                        VerticalLayout {
                        vertical-stretch: 1;
                        spacing: 4px;

                        HorizontalLayout {
                            vertical-stretch: 1;
                            min-height: 45px;
                            alignment: LayoutAlignment.space-around;

                            ParamKnob {
                                param_name: "input_svf_cutoff_low_l";
                                label: "Low L";
                                val: ParamBus.read_val("input_svf_cutoff_low_l");
                                display_val: ParamBus.read_display_val("input_svf_cutoff_low_l");
                            }
                            ParamKnob {
                                param_name: "input_svf_cutoff_high_l";
                                label: "High L";
                                val: ParamBus.read_val("input_svf_cutoff_high_l");
                                display_val: ParamBus.read_display_val("input_svf_cutoff_high_l");
                            }
                        }

                        HorizontalLayout {
                            vertical-stretch: 1.6;
                            min-height: 75px;
                            alignment: LayoutAlignment.space-around;

                            Timing {
                                bpm_param: "bpm_bound_l";
                                ms_param: "delay_l";
                                note_param: "delay_note_l";
                                div_param: "delay_div_l";
                                selected_factor: root.timing_factor_l;
                                note_display: root.timing_display_l;
                                time_ms: ParamBus.read_val("delay_l");
                                display_time_ms: ParamBus.read_display_val("delay_l");
                                time_16th: ParamBus.read_val("delay_note_l");
                                bpm_bound <=> root.is_bpm_bound_l;
                            }
                        }

                        HorizontalLayout {
                            vertical-stretch: 1;
                            min-height: 55px;
                            alignment: LayoutAlignment.space-around;

                            ParamKnob {
                                param_name: "feedback_l";
                                label: "FB L";
                                val: ParamBus.read_val("feedback_l");
                                display_val: ParamBus.read_display_val("feedback_l");
                            }

                            ParamKnob {
                                param_name: "wetness";
                                label: "Wetness";
                                val: ParamBus.read_val("wetness");
                            }
                        }
                    }

                    if open_page == 1:
                        VerticalLayout {
                        vertical-stretch: 1;
                        spacing: 4px;

                        HorizontalLayout {
                            vertical-stretch: 1;
                            min-height: 45px;
                            alignment: LayoutAlignment.space-around;

                            ParamKnob {
                                param_name: "input_svf_cutoff_low_r";
                                label: "Low R";
                                val: ParamBus.read_val("input_svf_cutoff_low_r");
                                display_val: ParamBus.read_display_val("input_svf_cutoff_low_r");
                            }
                            ParamKnob {
                                param_name: "input_svf_cutoff_high_r";
                                label: "High R";
                                val: ParamBus.read_val("input_svf_cutoff_high_r");
                                display_val: ParamBus.read_display_val("input_svf_cutoff_high_r");
                            }
                        }

                        HorizontalLayout {
                            vertical-stretch: 1.6;
                            min-height: 75px;
                            alignment: LayoutAlignment.space-around;

                            Timing {
                                bpm_param: "bpm_bound_r";
                                ms_param: "delay_r";
                                note_param: "delay_note_r";
                                div_param: "delay_div_r";
                                selected_factor: root.timing_factor_r;
                                note_display: root.timing_display_r;
                                time_ms: ParamBus.read_val("delay_r");
                                display_time_ms: ParamBus.read_display_val("delay_r");
                                time_16th: ParamBus.read_val("delay_note_r");
                                bpm_bound <=> root.is_bpm_bound_r;
                            }
                        }

                        HorizontalLayout {
                            vertical-stretch: 1;
                            min-height: 55px;
                            alignment: LayoutAlignment.space-around;

                            ParamKnob {
                                param_name: "feedback_r";
                                label: "FB R";
                                val: ParamBus.read_val("feedback_r");
                            }

                            ParamKnob {
                                param_name: "wetness";
                                label: "Wetness";
                                val: ParamBus.read_val("wetness");
                            }
                        }
                    }
                }
            }
        }
    }
}
