import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch, Spinner, HorizontalBox
} from "std-widgets.slint";
import { ParamKnob } from "../components/param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "../components/param_switch.slint";
import { Palette } from "../global.slint";
import { PeakMeter } from "../components/peak_meter.slint";
import { SpectrumAnalyzer } from "../components/spectrum_analyzer.slint";
import { Button } from "../components/button.slint";
import { EditorBufferVisualizer } from "../components/editor_buffer_vis.slint";
import { IconButton } from "../components/icon_button.slint";

export component EditorPage inherits VerticalLayout {
    in property <image> editor_tex_l;
    in property <image> editor_tex_r;
    in-out property <float> read_head_l;
    in-out property <float> read_head_r;
    in-out property <float> write_head_l;
    in-out property <float> write_head_r;
    in-out property <bool> is_stereo;
    in-out property <bool> is_ping_pong;

    VerticalLayout {
        vertical-stretch: 1;
        spacing: 4px;
        EditorBufferVisualizer {
            horizontal-stretch: 1;
            texture: root.editor_tex_l;
            read_head <=> root.read_head_l;
            write_head <=> root.write_head_l;
        }
        EditorBufferVisualizer {
            horizontal-stretch: 1;
            texture: root.editor_tex_r;
            read_head <=> root.read_head_r;
            write_head <=> root.write_head_r;
            left_channel: true;
        }
    }
    HorizontalLayout {
        height: 25px;
        width: 10%;
        alignment: LayoutAlignment.center;
        spacing: 10px;
        IconButton {
            width: 25px;
            height: 25px;
            checked: !root.is_stereo;
            Image {
                source: @image-url("../assets/mono.svg");
                image-fit: contain;
                colorize: parent.checked ? Palette.text-dark : Palette.text;
            }

            clicked => {
                ParamBus.param_changed("stereo", 0.0);
            }
        }
        IconButton {
            width: 25px;
            height: 25px;
            checked: root.is_stereo && !is_ping_pong;
            Image {
                source: @image-url("../assets/stereo.svg");
                image-fit: contain;
                colorize: parent.checked ? Palette.text-dark : Palette.text;
            }

            clicked => {
                ParamBus.param_changed("stereo", 0.5);
            }
        }
        IconButton {
            width: 25px;
            height: 25px;
            checked: root.is_ping_pong;
            Image {
                source: @image-url("../assets/pingpong.svg");
                image-fit: contain;
                colorize: parent.checked ? Palette.text-dark : Palette.text;
            }

            clicked => {
                ParamBus.param_changed("stereo", 1.0);
            }
        }
    }
    HorizontalLayout {
        ParamKnob {
            param_name: "buffer_len_l";
            label: "Buffer_len_l";
            val: ParamBus.read_val("buffer_len_l");
        }
        ParamKnob {
            param_name: "buffer_len_r";
            label: "Buffer_len_r";
            val: ParamBus.read_val("buffer_len_r");
        }
    }
}