import { Palette } from "../global.slint";
export component Button inherits Rectangle {
    in property <string> text: "Button";
    in property <bool> checked: false;
    callback clicked();

    background: checked ? Palette.primary-muted : Palette.secondary-muted;

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => { root.clicked(); }
    }

    Text {
        text: root.text;
        color: checked ? Palette.text-dark : Palette.text;
        font-size: 14px;
        horizontal-alignment: center;
    }
}