 import { AboutSlint, VerticalBox, Slider } from "std-widgets.slint";
import { ParamBus } from "../events.slint";
import { Palette } from "./global.slint";

export component DecayVisualizer inherits Rectangle {
    in-out property <float> bpm: 120.0;
    in-out property <bool> is_stereo: false;
    in-out property <bool> is_ping_pong: false;
    in-out property <float> feedback_l: 0.5;
    in-out property <float> feedback_r: 0.9;

    // Skewed [0,1] of 10s
    in-out property <float> time_l: 0.1;
    in-out property <float> time_r: 0.14142136;

    // [0,1] -> [0,32]
    in-out property <float> time_note_l: 0.0625;
    in-out property <float> time_note_r: 0.0625;

    // 0,0.333,0.666,1 -> factors 1,2,4,8
    in-out property <float> time_div_l: 0.0;
    in-out property <float> time_div_r: 0.0;

    in-out property <bool> bpm_bound_l: false;
    in-out property <bool> bpm_bound_r: false;

    property <length> second_width: 100px;

    // ms skew to linear time: FloatRange::Skewed{0,5000,0.5} -> plain = pow(norm,2)*10000
    property <float> time_s_l: pow(time_l, 2.0) * 5.0;
    property <float> time_s_r: pow(time_r, 2.0) * 5.0;

    // notes to seconds via BPM: delay_time_from_bpm_and_16th(total_16th,bpm) = total_16th*60/bpm/4*1000
    property <float> div_factor_l: time_div_l < 0.166 ? 1.0 : (time_div_l < 0.5 ? 2.0 : (time_div_l < 0.833 ? 4.0 : 8.0));
    property <float> div_factor_r: time_div_r < 0.166 ? 1.0 : (time_div_r < 0.5 ? 2.0 : (time_div_r < 0.833 ? 4.0 : 8.0));

    property <float> total_16th_l: time_note_l * 16.0 * div_factor_l;
    property <float> total_16th_r: time_note_r * 16.0 * div_factor_r;

    property <float> time_s_beats_l: total_16th_l * 60.0 / bpm / 4.0;
    property <float> time_s_beats_r: total_16th_r * 60.0 / bpm / 4.0;

    property <length> bar_width: 240.0 / bpm * second_width;

    property <length> pp_double_step: ((bpm_bound_l ? time_s_beats_l : time_s_l) * second_width) + (bpm_bound_r ? time_s_beats_r : time_s_r) * second_width;

    background: Palette.background;
    clip: true;
    for i in 32: Rectangle {
        Rectangle {
            x:  (bpm_bound_l) ? i * bar_width : i * second_width;
            y: 0;
            width: 1px;
            height: root.height / 2.0;
            background: (bpm_bound_l) ? Palette.primary-muted : Palette.secondary-muted;
            opacity: 0.5;
        }
        Rectangle {
            x: (bpm_bound_r || (!is_stereo && bpm_bound_l)) ? i * bar_width : i * second_width;
            y: root.height / 2.0;
            width: 1px;
            height: root.height / 2.0;
            background: (bpm_bound_r || (!is_stereo && bpm_bound_l)) ? Palette.primary-muted : Palette.secondary-muted;
            opacity: 0.5;
        }
    }
    for i in 64: Rectangle {
        if !is_ping_pong:
        Rectangle {
            property <length> h: pow(feedback_l, i) * root.height / 2;
            x: (bpm_bound_l ? time_s_beats_l : time_s_l) * i * second_width;
            y: root.height / 2.0 - h;
            width: 5px;
            height: h > 1px ? h : 0;
            background: Palette.primary;
        }

        if !is_ping_pong && is_stereo:
        Rectangle {
            property <length> h: pow(feedback_r, i) * root.height / 2;
            x: (bpm_bound_r ? time_s_beats_r : time_s_r) * i * second_width;
            y: root.height / 2.0;
            width: 5px;
            height: h > 1px ? h : 0;
            background: Palette.secondary;
        }
        if !is_ping_pong && !is_stereo:
        Rectangle {
            property <length> h: pow(feedback_l, i) * root.height / 2;
            x: (bpm_bound_l ? time_s_beats_l : time_s_l) * i * second_width;
            y: root.height / 2;
            width: 5px;
            height: h > 1px ? h : 0;
            background: Palette.secondary;
        }

        // Ping pong gets four lines of decays
        for i in 16:
        Rectangle {
            // primary
            if is_ping_pong:
            Rectangle {
                property <length> h: pow(feedback_l, i * 2) * root.height / 2;
                background: Palette.primary;
                width: 5px;
                height: h > 1px ? h : 0;
                y: root.height / 2.0;
                x: i * pp_double_step;
            }
            if is_ping_pong:
            Rectangle {
                property <length> h: pow(feedback_l, i * 2 + 1) * root.height / 2;
                background: Palette.primary;
                width: 5px;
                height: h > 1px ? h : 0;
                y: root.height / 2.0 - h;
                x: i * pp_double_step + (bpm_bound_l ? time_s_beats_l : time_s_l) * second_width;
            }
            // secondary
            if is_ping_pong:
            Rectangle {
                property <length> h: pow(feedback_r, i * 2) * root.height / 2;
                background: Palette.secondary;
                width: 5px;
                height: h > 1px ? h : 0;
                y: root.height / 2.0 - h;
                x: i * pp_double_step;
            }
            if is_ping_pong:
            Rectangle {
                property <length> h: pow(feedback_r, i * 2 + 1) * root.height / 2;
                background: Palette.secondary;
                width: 5px;
                height: h > 1px ? h : 0;
                y: root.height / 2.0;
                x: i * pp_double_step + (bpm_bound_l ? time_s_beats_r : time_s_r) * second_width;
            }
        }
    }
}
