import { ParamKnob } from "param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "param_switch.slint";

export component DiffusorFilter inherits HorizontalLayout {
    property <bool> active: ParamBus.read_val("eq_active") > 0.5;
    alignment: center;

    opacity: root.active ? 1.0 : 0.5;
    VerticalLayout {
        alignment: center;
        Text {
            text: "Diffusion";
        }
    }
    HorizontalLayout {
        Text {
            text: "Diffusion";
        }

        ParamKnob {
            param_name: "dattorro_size";
            label: "Size";
            val: ParamBus.read_val("dattorro_size");
        }
        ParamKnob {
            param_name: "dattorro_lushness";
            label: "Lushness";
            val: ParamBus.read_val("dattorro_lushness");
        }
        ParamKnob {
            param_name: "dattorro_brightness";
            label: "Brightness";
            val: ParamBus.read_val("dattorro_brightness");
        }

        ParamKnob {
            param_name: "dattorro_decay";
            label: "Decay";
            val: ParamBus.read_val("dattorro_decay");
        }

        ParamKnob {
            param_name: "dattorro_pre_delay";
            label: "Pre Delay";
            val: ParamBus.read_val("dattorro_pre_delay");
        }
        ParamKnob {
            param_name: "dattorro_mix";
            label: "Mix";
            val: ParamBus.read_val("dattorro_mix");
        }
    }
    VerticalLayout {
        alignment: center;
        ParamSwitch {
            param_name: "diffusor_active";
            checked <=> root.active;
        }
    }
}
