import { VerticalBox, Slider } from "std-widgets.slint";
import { ParamBus } from "../events.slint";
import { Palette, UIJump, UIJumpSegment, UIPortal } from "../global.slint";
import { IconButton } from "icon_button.slint";

export component EditorBufferVisualizer inherits Rectangle {
    in-out property <image> texture;
    in-out property <float> read_head;
    in-out property <float> write_head;
    in property <bool> left_channel;
    in property <[UIJump]> read_jumps;
    in property <[UIJump]> write_jumps;
    in property <[UIJumpSegment]> read_segments;
    in property <[UIJumpSegment]> write_segments;
    in property <[UIPortal]> read_portals;

    callback segment-swapped(int, int);
    callback segment-boundary-moved(int, float);
    callback portal-unglued(int);
    callback portal-reweld(int);
    callback portal-exit-moved(int, float);
    callback portal-entry-moved(int, float);
    callback segment-split(int);
    callback segments-merged(int);

    private property <int> selected: -1;
    VerticalLayout {
        if !left_channel:
        Rectangle {
            height: 13px;
            Text {
                x: max(0, min(write_head * root.width - self.width / 2, root.width - self.width));
                y: 0;
                font-size: 13px;
                text: "W";
                color: Palette.text;
                height: parent.height;
                horizontal-alignment: center;
            }
            Text {
                x: max(0, min(read_head * root.width - self.width / 2, root.width - self.width));
                y: 0;
                font-size: 13px;
                text: "R";
                color: Palette.text;
                height: parent.height;
                horizontal-alignment: center;
            }
        }
        Rectangle {
            vertical-stretch: 1;
            Image {
                source:  root.texture;
                width: 100%;
                height: parent.height;
            }
            Rectangle {
                x: read_head * root.width;
                height: parent.height;
                width: 1px;
                background: Palette.primary;
                clip: false;
            }
            Rectangle {
                x: write_head * root.width;
                height: parent.height;
                width: 1px;
                background: Palette.secondary;
                clip: false;
            }
            for segment[idx] in read_segments:
            Rectangle {
                x: segment.start * root.width;
                height: parent.height / 2;
                y: 0;
                width: (segment.end - segment.start) * root.width;
                background: @linear-gradient(90deg, Palette.primary.transparentize(0.8) 0%, #00000000 50%, Palette.primary.transparentize(0.8) 100%);
                clip: false;
                border-width: root.selected == idx ? 2px : 0px;
                border-color: Palette.primary;
                property <bool> hovered: false;
                Text {                   
                    x: parent.width / 2;
                    y: parent.height / 2;
                    text: segment.order + 1;
                    color: Palette.text-muted;
                }
                ta := TouchArea {
                    mouse-cursor: pointer;

                    pointer-event(event) => {
                        // if event.kind == PointerEventKind.up && event.button == PointerEventButton.left {
                        //     root.segment-split(idx)
                        // }
                        
                        if event.kind == PointerEventKind.up && event.button == PointerEventButton.right {
                            root.segments-merged(idx)
                        }
                    }
                    
                }
                split-btn := IconButton {
                    visible: ta.has-hover || split-btn.hovered;
                    width: 20px;
                    height: 20px;
                    enabled: true;
                    x: (parent.width / 2) - (self.width / 2);
                    y: parent.height - (self.height / 2);
                    Image {
                        source: @image-url("../assets/split.svg");
                        image-fit: contain;
                    }

                    clicked => {
                        root.segment-split(idx)
                    }
                }
            }
            for segment in write_segments:
            Rectangle {
                x: segment.start * root.width;
                height: parent.height / 2;
                y: parent.height / 2;
                width: (segment.end - segment.start) * root.width;
                background: @linear-gradient(90deg, Palette.secondary 0%, #00000000 50%, Palette.secondary 100%);
                opacity: 0.2;
                clip: false;
                Text {
                    x: parent.width / 2;
                    y: parent.height / 2;
                    text: segment.order + 1;
                    color: Palette.text-muted;
                }
            }

        }
        if left_channel:
        Rectangle {
            height: 10px;
            Text {
                x: max(0, min(write_head * root.width - self.width / 2, root.width - self.width));
                y: 0;
                font-size: 10px;
                text: "W";
                color: Palette.text;
                height: parent.height;
                horizontal-alignment: center;
            }
            Text {
                x: max(0, min(read_head * root.width - self.width / 2, root.width - self.width));
                y: 0;
                font-size: 10px;
                text: "R";
                color: Palette.text;
                height: parent.height;
                horizontal-alignment: center;
            }
        }
    }
}