import { ParamKnob } from "param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "param_switch.slint";

export component EQFilter inherits HorizontalLayout {
    property <int> tab: 0;
    property <bool> active: ParamBus.read_val("eq_active") > 0.5;
    opacity: root.active ? 1.0 : 0.5;
    VerticalLayout {
        alignment: center;
        Text {
            text: "EQ";
        }
    }
    if tab == 0:
    HorizontalLayout {
        ParamKnob {
            param_name: "svf_filter_mode_l";
            label: "Type";
            val: ParamBus.read_val("svf_filter_mode_l");
            display_val: ParamBus.read_display_val("svf_filter_mode_l");
        }
        ParamKnob {
            param_name: "svf_cutoff_l";
            label: "Cutoff";
            val: ParamBus.read_val("svf_cutoff_l");
            display_val: ParamBus.read_display_val("svf_cutoff_l");
        }
        ParamKnob {
            param_name: "svf_res_l";
            label: "Res";
            val: ParamBus.read_val("svf_res_l");
            display_val: ParamBus.read_display_val("svf_res_l");
        }
        ParamKnob {
            param_name: "svf_mix_l";
            label: "Mix";
            val: ParamBus.read_val("svf_mix_l");
            display_val: ParamBus.read_display_val("svf_mix_l");
        }
    }
    if tab == 1:
    HorizontalLayout {
        ParamKnob {
                param_name: "svf_filter_mode_r";
            label: "Type";
            val: ParamBus.read_val("svf_filter_mode_r");
            display_val: ParamBus.read_display_val("svf_filter_mode_r");
        }
         ParamKnob {
            param_name: "svf_cutoff_r";
            label: "Cutoff";
            val: ParamBus.read_val("svf_cutoff_r");
            display_val: ParamBus.read_display_val("svf_cutoff_r");
        }
        ParamKnob {
            param_name: "svf_res_r";
            label: "Res";
            val: ParamBus.read_val("svf_res_r");
            display_val: ParamBus.read_display_val("svf_res_r");
        }
        ParamKnob {
            param_name: "svf_mix_r";
            label: "Mix";
            val: ParamBus.read_val("svf_mix_r");
            display_val: ParamBus.read_display_val("svf_mix_r");
        }
    }
    VerticalLayout {
        alignment: center;
        ParamSwitch {
            param_name: "eq_active";
            checked <=> root.active;
        }
    }
}