import { ParamKnob } from "param_knob.slint";
import { ParamBus } from "../events.slint";
import { ParamSwitch } from "param_switch.slint";
import { Palette } from "../global.slint";
import { IconButton } from "icon_button.slint";

export component FilterEffect inherits Rectangle {
    property <int> tab: 0;
    property <bool> active: ParamBus.read_val("eq_active") > 0.5;
    property <bool> is_stereo: ParamBus.read_val("svf_stereo_mode") > 0.5;

    opacity: root.active ? 1.0 : 0.5;
    background: Palette.background-light;
    HorizontalLayout {
        padding-left: 1rem;
        padding-right: 1rem;
        alignment: space-evenly;
        VerticalLayout {
            alignment: center;
            Text {
                text: "Filter";
                color: Palette.text;
            }
        }
        VerticalLayout {
            alignment: center;
            spacing: 0.25rem;
            IconButton {
                width: 25px;
                height: 25px;
                checked: !root.is_stereo;
                Image {
                    source: @image-url("../assets/mono.svg");
                    image-fit: contain;
                    colorize: parent.checked ? Palette.text-dark : Palette.text;
                }

                clicked => {
                    ParamBus.param_changed("svf_stereo_mode", 0.0);
                }
            }
            IconButton {
                width: 25px;
                height: 25px;
                checked: root.is_stereo;
                Image {
                    source: @image-url("../assets/stereo.svg");
                    image-fit: contain;
                    colorize: parent.checked ? Palette.text-dark : Palette.text;
                }

                clicked => {
                    ParamBus.param_changed("svf_stereo_mode", 1.0);
                }
            }
        }
        if is_stereo:
        VerticalLayout {
            VerticalLayout {
                alignment: center;
                spacing: 0.25rem;
                IconButton {
                    width: 25px;
                    height: 25px;
                    checked: tab == 0;
                    Text {
                        text: "L";
                        color: parent.checked ? Palette.text-dark : Palette.text;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    clicked => {
                        tab = 0;
                    }
                }
                IconButton {
                    width: 25px;
                    height: 25px;
                    checked: tab == 1;
                    Text {
                        text: "R";
                        color: parent.checked ? Palette.text-dark : Palette.text;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    clicked => {
                        tab = 1;
                    }
                }
            }
        }
        if tab == 0:
        HorizontalLayout {
            ParamKnob {
                param_name: "svf_filter_mode_l";
                label: "Type";
                val: ParamBus.read_val("svf_filter_mode_l");
                display_val: ParamBus.read_display_val("svf_filter_mode_l");
            }
            ParamKnob {
                param_name: "svf_cutoff_l";
                label: "Cutoff";
                val: ParamBus.read_val("svf_cutoff_l");
                display_val: ParamBus.read_display_val("svf_cutoff_l");
            }
            ParamKnob {
                param_name: "svf_res_l";
                label: "Res";
                val: ParamBus.read_val("svf_res_l");
            }
            ParamKnob {
                param_name: "svf_mix_l";
                label: "Mix";
                val: ParamBus.read_val("svf_mix_l");
            }
        }
        if tab == 1:
        HorizontalLayout {
            ParamKnob {
                    param_name: "svf_filter_mode_r";
                label: "Type";
                val: ParamBus.read_val("svf_filter_mode_r");
                display_val: ParamBus.read_display_val("svf_filter_mode_r");
            }
             ParamKnob {
                param_name: "svf_cutoff_r";
                label: "Cutoff";
                val: ParamBus.read_val("svf_cutoff_r");
                display_val: ParamBus.read_display_val("svf_cutoff_r");
            }
            ParamKnob {
                param_name: "svf_res_r";
                label: "Res";
                val: ParamBus.read_val("svf_res_r");
            }
            ParamKnob {
                param_name: "svf_mix_r";
                label: "Mix";
                val: ParamBus.read_val("svf_mix_r");
            }
        }
        VerticalLayout {
            alignment: center;
            ParamSwitch {
                param_name: "eq_active";
                checked <=> root.active;
            }
        }
    }
}