export global Palette {
    in-out property <color> text: #fffffa;
    in-out property <color> text-muted: #C8C8C8;
    in-out property <color> primary: #ffd60a;
    in-out property <color> primary-muted: #DBA800;
    in-out property <color> secondary: #008fba;
    in-out property <color> secondary-muted: #003566;
    in-out property <color> background: #000814;
    in-out property <color> background-light: #001730;
}