import { AboutSlint, VerticalBox, Slider } from "std-widgets.slint";
import { ParamBus } from "../events.slint";
import {Palette} from "./global.slint";

export component PeakMeter inherits Rectangle {
    in-out property <float> val: 0.0;
    private property <float> follower: 0.0;
    width: 100px;
    height: 5px;

    background: Palette.secondary-muted;
    meter_rect := Rectangle {
        width: val * parent.width;
        height: parent.height;
        background: Palette.primary;
        x: 0;
    }

}