import { Palette } from "../global.slint";

export component SegmentHandle inherits Rectangle {
    in property <bool> hovered: false;
    in property <bool> active: false;

    width: 100%;
    height: 30%;

    background: @linear-gradient(180deg,
    Palette.primary                    0%,
    Palette.primary.transparentize(0.6) 45%,
    Palette.primary.transparentize(1)   100%);

    animate opacity {
        duration: 120ms;
        easing: ease-out;
    }
    opacity: root.hovered ? 1.0 : 0.0;
}