import { AboutSlint, VerticalBox, Slider } from "std-widgets.slint";
import { ParamBus } from "../events.slint";
import {Palette} from "./global.slint";

export component SpectrumAnalyzer inherits Rectangle {
    in-out property <[float]> bins: [1.0, 0.2, 0.5, 0.3, 0.7, 0.5, 0.3, 0.1, 0.5, 0.3, 0.0, 0.5, 0.3, 0.2, 0.5, 0.3, 0.2, 0.5, 0.3, 0.2, 0.5, 0.3, 0.2, 0.5, 0.3];
    in-out property <image> texture;
    Image {
        source:  root.texture;
        width: 100%;
        height: 100%;
    }
    /*
        background: Palette.secondary-muted;
        for bin[index] in root.bins:
            Rectangle {
                x: index * (root.width / root.bins.length);
                y: root.height - bin*root.height;
                width: (root.width / root.bins.length) - 1px;
                height: bin*root.height;
                background: Palette.primary;
            }

    */

}