import {
    Slider,
    VerticalBox,
    AboutSlint,
    CheckBox,
    Switch,
    Spinner,
    HorizontalBox,
} from "std-widgets.slint";
import { ParamKnob } from "components/param_knob.slint";
import { ParamBus } from "events.slint";
import { ParamSwitch } from "components/param_switch.slint";
import { Palette } from "./global.slint";
import { PeakMeter } from "components/peak_meter.slint";
import { SpectrumAnalyzer } from "components/spectrum_analyzer.slint";
import { Button } from "components/button.slint";
import { AboutPage } from "pages/about_page.slint";
import { EditorPage } from "pages/editor_page.slint";
import { FilterPage } from "pages/effects_page.slint";
import { DelayPage } from "pages/delay_page.slint";
export { ParamBus }
export struct FilterData {
    filter_order: [string],
}

export struct HeaderData {
    in_level_l: float,
    in_level_r: float,
    out_level_l: float,
    out_level_r: float,
}

export struct MetaData {
    is_stereo: bool,
    is_ping_pong: bool,
    is_filter_stereo: bool,
    is_bpm_bound_l: bool,
    is_bpm_bound_r: bool,
    version: string,
    bpm: float
}

export struct EditorData {
    write_head_l: float,
    write_head_r: float,
    read_head_l: float,
    read_head_r: float
}

export struct Textures {
    spectrum: image,
    buffer: image,
    decay: image,
    editor_buffer_l: image,
    editor_buffer_r: image
}
export component AppWindow inherits Window {
    in-out property <FilterData> filter_data;
    in-out property <HeaderData> header_data;
    in-out property <EditorData> editor_data;
    in-out property <Textures> textures;


    in-out property <bool> is_stereo: false;
    in-out property <bool> is_ping_pong: false;
    in-out property <bool> is_filter_stereo: false;
    in-out property <bool> is_bpm_bound_l: false;
    in-out property <bool> is_bpm_bound_r: false;

    in-out property <string> timing_display_l: "2 16th";
    in-out property <string> timing_display_r: "2 16th";
    in-out property <float> timing_factor_l: 1.0;
    in-out property <float> timing_factor_r: 1.0;

    in-out property <[float]> dry_buffer;
    in-out property <[float]> wet_buffer;
    in-out property <string> version;
    in-out property <float> bpm;

    private property <int> tab: 0;

    background: Palette.background;
    width: 550px;
    height: 350px;
    title: "Delax";

    main-content := VerticalLayout {
        padding: 0px;
        spacing: 4px;
        vertical-stretch: 1;
        alignment: stretch;

        top-bar := HorizontalLayout {
            padding: 5px;
            spacing: 6px;
            alignment: LayoutAlignment.space-between;
            Image {
                source: @image-url("assets/logo.svg");
                width: 60px;
                height: 22px;
                horizontal-alignment: ImageHorizontalAlignment.left;
                image-fit: ImageFit.contain;
            }

            HorizontalLayout {
                spacing: 5px;
                alignment: LayoutAlignment.center;
                Button {
                    checked: tab == 0;
                    text: "Delay";
                    width: 52px;
                    height: 24px;
                    clicked => {
                        tab = 0;
                    }
                }

                Button {
                    checked: tab == 1;
                    text: "Effects";
                    width: 52px;
                    height: 24px;
                    clicked => {
                        tab = 1;
                    }
                }

                Button {
                    checked: tab == 2;
                    text: "Editor";
                    width: 52px;
                    height: 24px;
                    clicked => {
                        tab = 2;
                    }
                }
            }

            HorizontalLayout {
                spacing: 6px;
                alignment: LayoutAlignment.end;
                VerticalLayout {
                    alignment: LayoutAlignment.space-between;
                    VerticalLayout {
                        spacing: 1px;
                        PeakMeter {
                            val <=> header_data.in_level_l;
                        }

                        PeakMeter {
                            val <=> header_data.in_level_r;
                        }
                    }

                    VerticalLayout {
                        spacing: 1px;
                        PeakMeter {
                            val <=> header_data.out_level_l;
                        }

                        PeakMeter {
                            val <=> header_data.out_level_r;
                        }
                    }
                }

                SpectrumAnalyzer {
                    texture <=> root.textures.spectrum;
                    width: 100px;
                }
            }
        }
        pages := VerticalLayout {
            padding: 0px;
            vertical-stretch: 1;

            if tab == 0:
                DelayPage {
                buffer_tex: root.textures.buffer;
                decay_tex: root.textures.decay;
                vertical-stretch: 1;
                is-stereo <=> root.is_stereo;
                is-ping-pong <=> root.is_ping_pong;
                is-bpm-bound-l <=> root.is_bpm_bound_l;
                is-bpm-bound-r <=> root.is_bpm_bound_r;
                timing-display-l <=> root.timing_display_l;
                timing-display-r <=> root.timing_display_r;
                timing-factor-l <=> root.timing_factor_l;
                timing-factor-r <=> root.timing_factor_r;
                bpm <=> root.bpm;
                dry_buffer <=> dry_buffer;
                wet_buffer <=> wet_buffer;
            }
            if tab == 1:
                FilterPage {
                vertical-stretch: 1;
                is-filter-stereo <=> root.is_filter_stereo;
            }
            if tab == 2:
                EditorPage {
                editor_tex_l: root.textures.editor_buffer_l;
                editor_tex_r: root.textures.editor_buffer_r;
                vertical-stretch: 1;
                read_head_l: root.editor_data.read_head_l;
                write_head_l: root.editor_data.write_head_l;
                read_head_r: root.editor_data.read_head_r;
                write_head_r: root.editor_data.write_head_r;
                is_stereo <=> root.is_stereo;
                is_ping_pong <=> root.is_ping_pong;
            }
            if tab == 3:
                AboutPage {
                vertical-stretch: 1;
                version <=> root.version;
            }
        }
        bottom-bar := HorizontalLayout {
            max-height: 20px;
            spacing: 5px;
            padding-left: 2px;
            padding-right: 2px;
            alignment: LayoutAlignment.space-between;

            TouchArea {
                width: about-text.preferred-width;
                about-text := Text {
                    text: "About";
                    font-size: 8pt;
                    vertical-alignment: TextVerticalAlignment.center;
                    color: Palette.text-muted;
                }

                clicked => {
                    tab = 3;
                }
                mouse-cursor: pointer;
            }

            Image {
                source: @image-url("assets/handle.svg");
                height: 20px;
                width: 100px;
                horizontal-alignment: ImageHorizontalAlignment.right;
                image-fit: ImageFit.contain;
            }
        }

    }
}