name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: sudo apt install libasound2-dev libgl-dev libxcursor-dev libjack-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-icccm4-dev && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
